-- Run in Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  movie_title text not null,
  poster text,
  created_at timestamptz not null default now(),
  -- Required for Cinemind (TMDB show id + watchlist UI)
  movie_id bigint not null,
  watched boolean not null default false,
  liked boolean not null default false,
  user_rating numeric(3,1),
  unique (user_id, movie_id)
);

-- If table already exists:
-- alter table public.watchlist add column if not exists user_rating numeric(3,1);

create index if not exists watchlist_user_id_idx on public.watchlist (user_id);

alter table public.watchlist enable row level security;

-- Server uses the anon/publishable key; allow authenticated API to manage rows.
-- Tighten policies later if you move to Supabase Auth.
drop policy if exists "watchlist_all" on public.watchlist;
create policy "watchlist_all"
  on public.watchlist
  for all
  using (true)
  with check (true);
