-- Run in Supabase SQL Editor (Dashboard → SQL → New query)

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  movie_title text not null,
  poster text,
  created_at timestamptz not null default now(),
  -- Required for Cinemind (TMDB show id + watchlist UI)
  movie_id bigint not null,
  watched boolean not null default false,
  liked boolean not null default false,
  user_rating numeric(3,1),
  unique (user_id, movie_id)
);

-- Backfill/repair for existing tables created from older schema.
alter table public.watchlist add column if not exists movie_id bigint;
alter table public.watchlist add column if not exists watched boolean not null default false;
alter table public.watchlist add column if not exists liked boolean not null default false;
alter table public.watchlist add column if not exists user_rating numeric(3,1);

-- Optional: if you know every row should have movie_id, run this after backfilling values.
-- alter table public.watchlist alter column movie_id set not null;

drop index if exists watchlist_user_movie_idx;
drop index if exists watchlist_user_movie_id_idx;
drop index if exists watchlist_user_movie_unique_idx;
create unique index if not exists watchlist_user_movie_idx on public.watchlist (user_id, movie_id);
create index if not exists watchlist_user_id_idx on public.watchlist (user_id);

alter table public.watchlist enable row level security;

-- Server uses the anon/publishable key; allow authenticated API to manage rows.
-- Tighten policies later if you move to Supabase Auth.
drop policy if exists "watchlist_all" on public.watchlist;
create policy "watchlist_all"
  on public.watchlist
  for all
  using (true)
  with check (true);
